[package]
name = "portan-git"
authors = ["thesimplekid"]
license = "BSD 3-Clause OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
url = "2.3.1"
portan = { path = "../portan" }
